- name: Create Network Backup Play
  hosts: all
  gather_facts: false
  vars:
    data_store:
      scm:
        origin:
          user:
            name: "chagrawa123"
            email: "chagrawa123@outlook.com" 
          url: "https://github.com/chagrawa123/nvc_use_cases"
          token: "{{ lookup('env', 'gh_token') }}"
          path: "data/backups/22-09-2025/ios"
          filename: "ios_22_09_2025.txt"
  tasks:
    - name: Set host-level var (for AAP compatibility)
      set_fact:
        data_store: "{{ data_store }}"
    - name: Create Network Backup and Push to GitHub
      ansible.builtin.include_role:
        name: network.backup.backup
      
