- name: Create Network Restore Play
  hosts: network
  gather_facts: true
 
  tasks:
    - name: Restore network config from saved config
      ansible.builtin.include_role:
        name: network.backup.restore
      vars:
        data_store:
          scm:
            origin:
              user:
                name: "chagrawa123"
                email: "chagrawa123@outlook.com" 
              url: "https://github.com/chagrawa123/nvc_use_cases"
              token: "{{ lookup('env', 'gh_token') }}"
              filename: "ios_17_08_2025.txt"
              path: "data/backups/17-08-2025/ios"
